### PR TITLE
fixed contrast bug and adjusted some colors

### PR DESCRIPTION
**Pull request by Auxburger**
Hey! 

I saw some issues regarding the Atom One Light theme while using it. It did show the wrong name and did not use the contrast color. Thus, i took a look at your repo and found the fixes i guess.
Furthermore, i changed some colors for on the one hand readability (selectBg) and on the other hand consistency (background). 

I also got a Question regarding file colors. I saw that we provide colors in the themes.yml for _green_, _blue_ etc. for each theme but do not use them. I'd propose to use them for coloring the files in the template.theme.json:

```   
 "FileColor": {
      "Green": "#387002",
      "Blue": "#004BA0",
      "Yellow": "%excl",
      "Orange": "#B53D00",
      "Violet": "#4D2C91",
      "Rose": "#A00037"
    },
```   

For example the green color of the files is too dark for the One Light theme. The colors provided by each style in the themes.yml would be reasonable i guess. I'd then of course love to contribute another PR. 🔥  

Looking forward for feedback and suggestions. 😄

### CODE REVIEW

**Comment by Auxburger** [comment]
I just saw, that the naming bug was also called in [Issue 33](https://github.com/mallowigi/material-theme-ui-lite/issues/33#issue-855347801)

**Comment by mallowigi** [comment]
Good catch! Regarding the select color I need to make sure it fits.

Regarding you second question: the "green", "blue" etc from the themes.yml are used for the documentation, and relates to the "green", "red" etc of the color scheme. Therefore, having these as file colors are too bright to be useful.

Or maybe I didn't understand what you meant. Do you have a screenshot?

**Comment by Auxburger** [comment]
Sure, check it 😊 

Ah alright, the attached image shows the pretty dark green, which makes the text very unreadable and unfitting in comparison to the remaining tree in my opinion 🤔

**Comment by mallowigi** [comment]
Are these jetbrains default colors ?

**Comment by mallowigi** [comment]
Yeah that's the reason I had many other different colors in the main plugin, but still the syntax colors are not the right colors, they are way too bright.
Frankly in my opinion we should replace these colors with the theme ones (excluded is already available, but maybe other colors can be used such as contrast or highlight)

I have no idea

**Comment by Auxburger** [comment]
Yeah sounds good! 👍🏽

**Pull request closed without merging**
